version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  say-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello"
  say-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say world"
          command: "echo World"
  print-myname-var:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "print my name env variable"
          command: |
               echo $MY_NAME 
               echo $CIRCLE_BRANCH
  save_output_sharingfiles:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "this job is created to test file sharing in circleci" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_sharingfile:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
  test_commands:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id    
  test_job_failure:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: exit 1
      - run:
          name: on error
          command: echo "Hello Error!"
          when: on_fail    
            
workflows:
  welcome:
    jobs:
      - say-hello
      - say-world:
            requires:
                 - say-hello
      - print-myname-var
      - save_output_sharingfiles
      - print_output_sharingfile:
            requires:
                 - save_output_sharingfiles
      - test_commands
      - test_job_failure